-- MySQL Script generated by MySQL Workbench
-- 06/10/17 09:06:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Inventario` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Inventario` ;

-- -----------------------------------------------------
-- Table `Inventario`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventario`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombreCargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcargo`),
  UNIQUE INDEX `idrol_UNIQUE` (`idcargo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventario`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventario`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProd` VARCHAR(45) NOT NULL,
  `descripcionProd` VARCHAR(45) NOT NULL,
  `costo` DECIMAL(18,2) NOT NULL,
  `pvp` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventario`.`bodegueros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventario`.`bodegueros` (
  `idBodegueros` INT NOT NULL AUTO_INCREMENT,
  `cedula_ruc_pasaporte` INT NOT NULL,
  `nombreBodeguero` VARCHAR(45) NOT NULL,
  `apellidoBodeguero` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `ciudadNacimiento` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idBodegueros`),
  INDEX `fk_bodegueros_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_bodegueros_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `Inventario`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventario`.`ajustes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventario`.`ajustes` (
  `idAjustes` INT NOT NULL AUTO_INCREMENT,
  `detalleAjuste` VARCHAR(45) NOT NULL,
  `fechaAjuste` DATE NOT NULL,
  `numeroAjuste` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idAjustes`, `producto_idproducto`),
  INDEX `fk_ajustes_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_ajustes_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `Inventario`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventario`.`detalle_ajustes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventario`.`detalle_ajustes` (
  `idDetalle_Ajustes` INT NOT NULL AUTO_INCREMENT,
  `stok` INT NOT NULL,
  `ajustes_idAjustes` INT NOT NULL,
  `ajustes_producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idDetalle_Ajustes`, `ajustes_idAjustes`, `ajustes_producto_idproducto`),
  INDEX `fk_detalle_ajustes_ajustes1_idx` (`ajustes_idAjustes` ASC, `ajustes_producto_idproducto` ASC),
  CONSTRAINT `fk_detalle_ajustes_ajustes1`
    FOREIGN KEY (`ajustes_idAjustes` , `ajustes_producto_idproducto`)
    REFERENCES `Inventario`.`ajustes` (`idAjustes` , `producto_idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
